import { useCallback, useEffect, useMemo, useState } from "react";
import { supabase } from "../supabaseClient";
import type { Client, Lead, SalesTask } from "../types";
import { connectGoogleCalendar, createGoogleCalendarEvent, deleteGoogleCalendarEvent, googleCalendarConfigured, googleCalendarConnected, googleFreeBusy, listGoogleCalendarEvents, OWNER_CALENDAR_ID, updateGoogleCalendarEvent, type GoogleEvent } from "../calendarGoogle";

const romeDay = (d: Date) => d.toLocaleDateString("en-CA", { timeZone: "Europe/Rome" });
const formatTime = (iso: string) => new Intl.DateTimeFormat("it-IT", { hour: "2-digit", minute: "2-digit", timeZone: "Europe/Rome" }).format(new Date(iso));
const formatDateTime = (iso: string) => new Intl.DateTimeFormat("it-IT", { weekday: "long", day: "numeric", month: "long", hour: "2-digit", minute: "2-digit", timeZone: "Europe/Rome" }).format(new Date(iso));
const monday = (value: Date) => { const date = new Date(value); date.setHours(0, 0, 0, 0); date.setDate(date.getDate() - ((date.getDay() + 6) % 7)); return date; };
const eventDay = (event: GoogleEvent) => event.start?.dateTime ? romeDay(new Date(event.start.dateTime)) : event.start?.date || "";
const eventTime = (event: GoogleEvent) => event.start?.dateTime ? formatTime(event.start.dateTime) : "Tutto il giorno";
const localDateTime = (date: Date) => { const pad = (n: number) => String(n).padStart(2, "0"); return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}`; };
const eventEnd = (task: SalesTask) => new Date(new Date(task.due_at).getTime() + 60 * 60 * 1000);
type Selected = { kind: "crm"; task: SalesTask; lead: Lead | null } | { kind: "google"; event: GoogleEvent };
type TimedCalendarItem = { kind: "crm"; at: string; endAt: string; task: SalesTask } | { kind: "google"; at: string; endAt: string; event: GoogleEvent };

function overlapGroups(items: TimedCalendarItem[]) {
  const groups: TimedCalendarItem[][] = []; let current: TimedCalendarItem[] = []; let latestEnd = 0;
  items.forEach((item) => { const start = new Date(item.at).getTime(); const end = new Date(item.endAt).getTime(); if (current.length && start >= latestEnd) { groups.push(current); current = []; latestEnd = 0; } current.push(item); latestEnd = Math.max(latestEnd, end); });
  if (current.length) groups.push(current);
  return groups;
}

export default function Calendar({ client, meName }: { client: Client; meName: string }) {
  const [tasks, setTasks] = useState<SalesTask[]>([]); const [leads, setLeads] = useState<Lead[]>([]); const [google, setGoogle] = useState<GoogleEvent[]>([]);
  const [selected, setSelected] = useState<Selected | null>(null); const [createOpen, setCreateOpen] = useState(false); const [editingEvent, setEditingEvent] = useState(false); const [weekStart, setWeekStart] = useState(() => monday(new Date()));
  const [title, setTitle] = useState(""); const [startsAt, setStartsAt] = useState(""); const [duration, setDuration] = useState("60"); const [note, setNote] = useState(""); const [leadId, setLeadId] = useState("");
  const [editTitle, setEditTitle] = useState(""); const [editStartsAt, setEditStartsAt] = useState(""); const [editNote, setEditNote] = useState(""); const [editError, setEditError] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null); const [formError, setFormError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const weekEnd = useMemo(() => { const date = new Date(weekStart); date.setDate(date.getDate() + 7); return date; }, [weekStart]);
  const days = useMemo(() => Array.from({ length: 7 }, (_, index) => { const date = new Date(weekStart); date.setDate(date.getDate() + index); return date; }), [weekStart]);
  const load = useCallback(async () => {
    const [taskResult, leadResult] = await Promise.all([supabase.from("sales_tasks").select("*").eq("client_id", client.id).gte("due_at", weekStart.toISOString()).lt("due_at", weekEnd.toISOString()).order("due_at"), supabase.from("leads").select("*").eq("client_id", client.id)]);
    setTasks((taskResult.data as SalesTask[]) || []); setLeads((leadResult.data as Lead[]) || []);
    if (googleCalendarConnected()) { try { setGoogle(await listGoogleCalendarEvents(weekStart, weekEnd)); } catch { setGoogle([]); } } else setGoogle([]);
  }, [client.id, weekEnd, weekStart]);
  useEffect(() => { void load(); }, [load]);
  const leadById = useMemo(() => new Map(leads.map((lead) => [lead.id, lead])), [leads]);
  const rangeLabel = `${weekStart.toLocaleDateString("it-IT", { day: "numeric", month: "short" })} – ${new Date(weekEnd.getTime() - 86400000).toLocaleDateString("it-IT", { day: "numeric", month: "short", year: "numeric" })}`;
  async function connect() { setBusy(true); setError(null); try { await connectGoogleCalendar(); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Collegamento non riuscito."); } setBusy(false); }
  function shiftWeek(amount: number) { setSelected(null); setWeekStart((current) => { const next = new Date(current); next.setDate(next.getDate() + amount * 7); return next; }); }
  function openCreate(date = new Date()) { const initial = new Date(date); initial.setHours(10, 0, 0, 0); if (initial < new Date()) initial.setTime(Math.ceil(Date.now() / 1_800_000) * 1_800_000); setTitle(""); setStartsAt(localDateTime(initial)); setDuration("60"); setNote(""); setLeadId(""); setFormError(null); setCreateOpen(true); }
  async function saveAppointment() {
    if (!title.trim() || !startsAt) return setFormError("Inserisci titolo, data e ora.");
    if (!googleCalendarConnected()) return setFormError("Collega prima Google Calendar: così l'appuntamento viene salvato in entrambi i calendari.");
    const start = new Date(startsAt); const minutes = Number(duration); const end = new Date(start.getTime() + minutes * 60_000);
    if (Number.isNaN(start.getTime()) || !minutes || minutes < 15) return setFormError("Controlla data, ora e durata.");
    setBusy(true); setFormError(null);
    let crm: { data: SalesTask[] | null; error: { message: string } | null }; let busySlots: Array<{ start: string; end: string }>;
    try {
      [crm, busySlots] = await Promise.all([
        supabase.from("sales_tasks").select("*").eq("client_id", client.id).gte("due_at", new Date(start.getTime() - 60 * 60 * 1000).toISOString()).lt("due_at", end.toISOString()),
        googleFreeBusy(start, end),
      ]);
    } catch {
      setBusy(false); return setFormError("Ricollega Google Calendar e riprova: serve per verificare che la fascia sia libera.");
    }
    if (crm.error) { setBusy(false); return setFormError("Non riesco a verificare gli appuntamenti CRM: " + crm.error.message); }
    const crmConflict = ((crm.data as SalesTask[]) || []).some((task) => new Date(task.due_at) < end && eventEnd(task) > start);
    if (crmConflict || busySlots.some((slot) => new Date(slot.start) < end && new Date(slot.end) > start)) { setBusy(false); return setFormError("Quella fascia è già occupata. Scegli un altro orario per evitare sovrapposizioni."); }
    const linkedLead = leadId ? leadById.get(leadId) || null : null;
    const cleanTitle = `Appuntamento — ${title.trim()}`;
    const description = [linkedLead ? `Lead: ${linkedLead.name || "Senza nome"}` : "", linkedLead?.phone ? `Telefono: ${linkedLead.phone}` : "", note.trim()].filter(Boolean).join("\n");
    const { error: insertError } = await supabase.from("sales_tasks").insert({ client_id: client.id, lead_id: leadId || null, title: cleanTitle, description: description || null, due_at: start.toISOString(), assigned_to: linkedLead?.assigned_to || meName || "Venditore", created_by: meName || null });
    if (!insertError && leadId) await supabase.from("leads").update({ next_action_date: startsAt.slice(0, 10) }).eq("id", leadId);
    if (insertError) { setBusy(false); return setFormError("Appuntamento non salvato: " + insertError.message); }
    try { await createGoogleCalendarEvent({ title: cleanTitle, start: start.toISOString(), end: end.toISOString(), description, attendees: [OWNER_CALENDAR_ID] }); } catch { setBusy(false); await load(); return setFormError("Appuntamento salvato nel CRM, ma Google non lo ha ricevuto. Ricollega Google Calendar e riprova."); }
    setBusy(false); setCreateOpen(false); await load();
  }
  const googleMatch = (task: SalesTask) => google.find((event) => event.summary === task.title && event.start?.dateTime && Math.abs(new Date(event.start.dateTime).getTime() - new Date(task.due_at).getTime()) < 60_000);
  function beginEdit() { if (!selected) return; const source = selected.kind === "crm" ? { title: selected.task.title.replace(/^Appuntamento —\s*/, ""), start: selected.task.due_at, note: selected.task.description || "" } : { title: selected.event.summary || "", start: selected.event.start?.dateTime || "", note: selected.event.description || "" }; if (!source.start) { setEditError("Gli eventi Google di intera giornata non sono modificabili dal CRM."); return; } setEditTitle(source.title); setEditStartsAt(localDateTime(new Date(source.start))); setEditNote(source.note); setEditError(null); setEditingEvent(true); }
  async function saveEventChanges() { if (!selected || !editTitle.trim() || !editStartsAt) return setEditError("Inserisci titolo, data e ora."); const start = new Date(editStartsAt); const end = new Date(start.getTime() + 60 * 60 * 1000); if (Number.isNaN(start.getTime())) return setEditError("Data o ora non valide."); setBusy(true); setEditError(null); try { if (selected.kind === "crm") { const nextTitle = `Appuntamento — ${editTitle.trim()}`; const { error: updateError } = await supabase.from("sales_tasks").update({ title: nextTitle, due_at: start.toISOString(), description: editNote.trim() || null }).eq("id", selected.task.id); if (updateError) throw new Error(updateError.message); const match = googleMatch(selected.task); if (match && googleCalendarConnected()) await updateGoogleCalendarEvent(match.id, { title: nextTitle, start: start.toISOString(), end: end.toISOString(), description: editNote.trim() }); setSelected({ kind: "crm", task: { ...selected.task, title: nextTitle, due_at: start.toISOString(), description: editNote.trim() || null }, lead: selected.lead }); } else { await updateGoogleCalendarEvent(selected.event.id, { title: editTitle.trim(), start: start.toISOString(), end: end.toISOString(), description: editNote.trim() }); setSelected({ kind: "google", event: { ...selected.event, summary: editTitle.trim(), description: editNote.trim(), start: { dateTime: start.toISOString() }, end: { dateTime: end.toISOString() } } }); } setEditingEvent(false); await load(); } catch (reason) { setEditError(reason instanceof Error ? reason.message : "Modifica non riuscita. Ricollega Google Calendar e riprova."); } setBusy(false); }
  async function deleteSelected() { if (!selected || !confirm("Eliminare questo appuntamento?")) return; setBusy(true); setEditError(null); try { if (selected.kind === "crm") { const match = googleMatch(selected.task); const { error: deleteError } = await supabase.from("sales_tasks").delete().eq("id", selected.task.id); if (deleteError) throw new Error(deleteError.message); if (match && googleCalendarConnected()) await deleteGoogleCalendarEvent(match.id); } else await deleteGoogleCalendarEvent(selected.event.id); setSelected(null); setEditingEvent(false); await load(); } catch (reason) { setEditError(reason instanceof Error ? reason.message : "Eliminazione non riuscita."); } setBusy(false); }

  return <div className="page calendar-page">
    <div className="calendar-intro"><div><div className="calendar-kicker">Agenda commerciale</div><h1>Calendario</h1><p>Appuntamenti CRM condivisi; Google personale privato. Nessuna sovrapposizione passa inosservata.</p></div><div className="calendar-top-actions"><button className="btn primary" type="button" onClick={() => openCreate()}>+ Nuovo appuntamento</button><div className="calendar-navigation"><button type="button" aria-label="Settimana precedente" onClick={() => shiftWeek(-1)}>‹</button><button type="button" onClick={() => { setSelected(null); setWeekStart(monday(new Date())); }}>Oggi</button><button type="button" aria-label="Settimana successiva" onClick={() => shiftWeek(1)}>›</button></div>{googleCalendarConfigured() ? <button className={`btn ${googleCalendarConnected() ? "" : "primary"}`} disabled={busy} onClick={() => void connect()}>{googleCalendarConnected() ? "Google collegato" : "Collega Google Calendar"}</button> : <span className="calendar-notice">Google Calendar da configurare</span>}</div></div>
    {error && <div className="notice err">{error}</div>}
    <div className="calendar-toolbar"><b>{rangeLabel}</b><span><i className="crm-dot" /> CRM condiviso <i className="google-dot" /> Il mio Google Calendar</span></div>
    <div className="calendar-week calendar-week-full" aria-label={`Settimana ${rangeLabel}`}>{days.map((date) => { const iso = romeDay(date); const isToday = iso === romeDay(new Date()); const local = tasks.filter((task) => romeDay(new Date(task.due_at)) === iso && !task.completed_at); const external = google.filter((event) => eventDay(event) === iso && !local.some((task) => task.title === event.summary && event.start?.dateTime && Math.abs(new Date(task.due_at).getTime() - new Date(event.start.dateTime).getTime()) < 60_000)); const allDay = external.filter((event) => !event.start?.dateTime); const timed: TimedCalendarItem[] = [...local.map((task) => ({ kind: "crm" as const, at: task.due_at, endAt: eventEnd(task).toISOString(), task })), ...external.filter((event) => event.start?.dateTime).map((event) => ({ kind: "google" as const, at: event.start?.dateTime || "", endAt: event.end?.dateTime || new Date(new Date(event.start?.dateTime || "").getTime() + 60 * 60 * 1000).toISOString(), event }))].sort((a, b) => a.at.localeCompare(b.at)); return <section key={iso} className={`calendar-column${isToday ? " today" : ""}`}><header><span>{date.toLocaleDateString("it-IT", { weekday: "short" })}</span><b>{date.getDate()}</b><button type="button" aria-label={`Nuovo appuntamento il ${date.toLocaleDateString("it-IT")}`} onClick={() => openCreate(date)}>+</button></header>{allDay.length > 0 && <div className="calendar-all-day">{allDay.map((event) => <button key={event.id} className="calendar-event google all-day" onClick={() => setSelected({ kind: "google", event })}><b>{event.summary || "Impegno Google"}</b></button>)}</div>}<div className="calendar-day-events">{overlapGroups(timed).map((group, index) => <div className={`calendar-event-row${group.length > 1 ? " overlapping" : ""}`} style={{ gridTemplateColumns: `repeat(${group.length}, minmax(0, 1fr))` }} key={`${group[0].at}-${index}`}>{group.map((item) => item.kind === "crm" ? <button key={item.task.id} className="calendar-event crm appointment" onClick={() => setSelected({ kind: "crm", task: item.task, lead: item.task.lead_id ? leadById.get(item.task.lead_id) || null : null })}><time>{formatTime(item.task.due_at)}</time><b>{item.task.title.replace(/^Appuntamento —\s*/, "")}</b><small>{item.task.lead_id ? leadById.get(item.task.lead_id)?.name || "Lead" : "Attività personale"}</small></button> : <button key={item.event.id} className="calendar-event google" onClick={() => setSelected({ kind: "google", event: item.event })}><time>{eventTime(item.event)}</time><b>{item.event.summary || "Impegno Google"}</b><small>Calendario personale</small></button>)}</div>)}</div>{!timed.length && !allDay.length && <button className="calendar-free" type="button" onClick={() => openCreate(date)}>Libero · aggiungi</button>}</section>; })}</div>
    {selected && <EventDetailsModal selected={selected} editing={editingEvent} title={editTitle} startsAt={editStartsAt} note={editNote} error={editError} busy={busy} onClose={() => { setSelected(null); setEditingEvent(false); }} onEdit={beginEdit} onCancelEdit={() => setEditingEvent(false)} onTitle={setEditTitle} onStartsAt={setEditStartsAt} onNote={setEditNote} onSave={() => void saveEventChanges()} onDelete={() => void deleteSelected()} />}
    {createOpen && <div className="calendar-modal-overlay" role="presentation" onClick={() => !busy && setCreateOpen(false)}><section className="calendar-modal calendar-create" role="dialog" aria-modal="true" aria-label="Nuovo appuntamento" onClick={(event) => event.stopPropagation()}><div className="calendar-detail-head"><span className="calendar-detail-label">Nuovo appuntamento</span><button type="button" aria-label="Chiudi" onClick={() => setCreateOpen(false)}>×</button></div><h2>Fissa appuntamento</h2><p className="calendar-create-copy">Verifichiamo prima le fasce CRM e Google, poi lo inseriamo in entrambi.</p>{formError && <div className="notice err">{formError}</div>}<label>Titolo<input autoFocus value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Es. Consulenza iniziale" /></label><div className="calendar-form-row"><label>Data e ora<input type="datetime-local" value={startsAt} onChange={(event) => setStartsAt(event.target.value)} /></label><label>Durata<select value={duration} onChange={(event) => setDuration(event.target.value)}><option value="30">30 min</option><option value="45">45 min</option><option value="60">1 ora</option><option value="90">1 ora e 30</option><option value="120">2 ore</option></select></label></div><label>Collega a un lead <small>(facoltativo)</small><select value={leadId} onChange={(event) => setLeadId(event.target.value)}><option value="">Nessun lead / appuntamento interno</option>{leads.slice().sort((a, b) => (a.name || "").localeCompare(b.name || "")).map((lead) => <option key={lead.id} value={lead.id}>{lead.name || "Senza nome"}{lead.phone ? ` · ${lead.phone}` : ""}</option>)}</select></label><label>Note <small>(facoltativo)</small><textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder="Contesto utile per l'appuntamento" /></label><footer><button className="btn" type="button" disabled={busy} onClick={() => setCreateOpen(false)}>Annulla</button><button className="btn primary" type="button" disabled={busy} onClick={() => void saveAppointment()}>{busy ? "Controllo disponibilità…" : "Crea appuntamento"}</button></footer></section></div>}
  </div>;
}

function EventDetailsModal({ selected, editing, title, startsAt, note, error, busy, onClose, onEdit, onCancelEdit, onTitle, onStartsAt, onNote, onSave, onDelete }: { selected: Selected; editing: boolean; title: string; startsAt: string; note: string; error: string | null; busy: boolean; onClose: () => void; onEdit: () => void; onCancelEdit: () => void; onTitle: (value: string) => void; onStartsAt: (value: string) => void; onNote: (value: string) => void; onSave: () => void; onDelete: () => void }) {
  const heading = selected.kind === "crm" ? selected.task.title.replace(/^Appuntamento —\s*/, "") : selected.event.summary || "Impegno Google";
  return <div className="calendar-modal-overlay" role="presentation" onClick={() => !busy && onClose()}><section className="calendar-modal calendar-event-modal" role="dialog" aria-modal="true" aria-label="Dettagli evento" onClick={(event) => event.stopPropagation()}><div className="calendar-detail-head"><span className={`calendar-detail-label${selected.kind === "google" ? " google-label" : ""}`}>{selected.kind === "google" ? "Evento Google personale" : "Appuntamento CRM"}</span><button type="button" aria-label="Chiudi dettagli" onClick={onClose}>×</button></div><h2>{editing ? "Modifica appuntamento" : heading}</h2>{error && <div className="notice err">{error}</div>}{editing ? <div className="calendar-event-edit"><label>Titolo<input autoFocus value={title} onChange={(event) => onTitle(event.target.value)} /></label><label>Data e ora<input type="datetime-local" value={startsAt} onChange={(event) => onStartsAt(event.target.value)} /></label><label>Note<textarea value={note} onChange={(event) => onNote(event.target.value)} /></label></div> : <><dl>{selected.kind === "crm" ? <><div><dt>Quando</dt><dd>{formatDateTime(selected.task.due_at)}</dd></div><div><dt>Durata</dt><dd>60 minuti</dd></div><div><dt>Assegnato a</dt><dd>{selected.task.assigned_to || "Non assegnato"}</dd></div>{selected.lead && <div><dt>Lead</dt><dd><b>{selected.lead.name || "Senza nome"}</b>{selected.lead.phone && <small>{selected.lead.phone}</small>}{selected.lead.email && <small>{selected.lead.email}</small>}</dd></div>}{selected.task.description && <div><dt>Dettagli</dt><dd>{selected.task.description}</dd></div>}</> : <><div><dt>Quando</dt><dd>{selected.event.start?.dateTime ? formatDateTime(selected.event.start.dateTime) : selected.event.start?.date || "Tutto il giorno"}</dd></div>{selected.event.location && <div><dt>Luogo</dt><dd>{selected.event.location}</dd></div>}{selected.event.description && <div><dt>Note</dt><dd>{selected.event.description}</dd></div>}</>}</dl><p className="calendar-detail-note">{selected.kind === "google" ? "Questo evento resta privato: non è visibile agli altri venditori." : "Selezionato nel calendario: non vieni riportato alla pipeline."}</p></>}<footer className="calendar-event-footer">{editing ? <><button className="btn" type="button" disabled={busy} onClick={onCancelEdit}>Annulla</button><button className="btn primary" type="button" disabled={busy} onClick={onSave}>{busy ? "Salvataggio…" : "Salva modifiche"}</button></> : <><button className="btn danger" type="button" disabled={busy} onClick={onDelete}>Elimina</button><button className="btn" type="button" onClick={onEdit}>Modifica</button></>}</footer></section></div>;
}
