import { useCallback, useEffect, useMemo, useState } from "react";
import { supabase } from "../supabaseClient";
import type { Client, Lead, SalesTask } from "../types";
import { connectGoogleCalendar, googleCalendarConfigured, googleCalendarConnected, listGoogleCalendarEvents } from "../calendarGoogle";

const day = (d: Date) => d.toLocaleDateString("en-CA", { timeZone: "Europe/Rome" });
const time = (iso: string) => new Intl.DateTimeFormat("it-IT", { hour: "2-digit", minute: "2-digit", timeZone: "Europe/Rome" }).format(new Date(iso));
export default function Calendar({ client, meName, onOpenLead }: { client: Client; meName: string; onOpenLead: (lead: Lead) => void }) {
  const [tasks, setTasks] = useState<SalesTask[]>([]); const [leads, setLeads] = useState<Lead[]>([]); const [google, setGoogle] = useState<any[]>([]); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const start = useMemo(() => { const d = new Date(); d.setHours(0,0,0,0); return d; }, []); const days = useMemo(() => Array.from({ length: 7 }, (_, i) => { const d = new Date(start); d.setDate(d.getDate()+i); return d; }), [start]);
  const load = useCallback(async () => { const [t,l] = await Promise.all([supabase.from("sales_tasks").select("*").eq("client_id", client.id).gte("due_at", start.toISOString()).lt("due_at", new Date(start.getTime()+7*86400000).toISOString()).order("due_at"), supabase.from("leads").select("*").eq("client_id", client.id)]); setTasks((t.data as SalesTask[]) || []); setLeads((l.data as Lead[]) || []); if (googleCalendarConnected()) { try { setGoogle(await listGoogleCalendarEvents(start, new Date(start.getTime()+7*86400000))); } catch { setGoogle([]); } } }, [client.id, start]);
  useEffect(() => { void load(); }, [load]); const leadById = useMemo(() => new Map(leads.map(l => [l.id,l])), [leads]);
  async function connect() { setBusy(true); setError(null); try { await connectGoogleCalendar(); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Collegamento non riuscito."); } setBusy(false); }
  return <div className="page calendar-page"><div className="calendar-intro"><div><h1>Calendario commerciale</h1><p>Appuntamenti e attività fissati dalla scheda lead. Il venditore collega soltanto il proprio Google Calendar.</p></div>{googleCalendarConfigured() ? <button className="btn primary" disabled={busy} onClick={() => void connect()}>{googleCalendarConnected() ? "Google Calendar collegato" : "Collega Google Calendar"}</button> : <span className="calendar-notice">Google Calendar da configurare</span>}</div>{error && <div className="notice err">{error}</div>}<div className="calendar-week">{days.map(d => { const iso=day(d); const local=tasks.filter(t => day(new Date(t.due_at))===iso && !t.completed_at); const external=google.filter(e => e.start?.dateTime && day(new Date(e.start.dateTime))===iso); return <section key={iso} className="calendar-column"><header><b>{d.toLocaleDateString("it-IT",{weekday:"short"})}</b><span>{d.getDate()}</span></header>{local.map(t => { const lead=t.lead_id ? leadById.get(t.lead_id) : null; const appointment=t.title.startsWith("Appuntamento —"); return <button className={`calendar-event ${appointment ? "appointment" : ""}`} key={t.id} onClick={() => lead && onOpenLead(lead)}><time>{time(t.due_at)}</time><b>{t.title}</b><small>{lead?.name || "Task personale"}</small></button>})}{external.map((e:any) => <div className="calendar-event google" key={e.id}><time>{e.start?.dateTime ? time(e.start.dateTime) : ""}</time><b>{e.summary || "Impegno Google"}</b></div>)}{!local.length && !external.length && <span className="calendar-free">Libero</span>}</section>; })}</div></div>;
}
