import { useCallback, useEffect, useMemo, useState } from "react";
import { supabase } from "../supabaseClient";
import type { Client, Lead, Pipeline, SalesTask, Stage } from "../types";
import { romeToday } from "../dates";

type View = "today" | "future" | "missing" | "done";
const localDateTime = (date = new Date()) => { const p = (n: number) => String(n).padStart(2, "0"); return `${date.getFullYear()}-${p(date.getMonth() + 1)}-${p(date.getDate())}T${p(date.getHours())}:${p(date.getMinutes())}`; };
const dayOf = (iso: string) => { const parts = new Intl.DateTimeFormat("it-IT", { timeZone: "Europe/Rome", year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(new Date(iso)); const value = (kind: string) => parts.find((part) => part.type === kind)?.value ?? ""; return `${value("year")}-${value("month")}-${value("day")}`; };
const timeOf = (iso: string) => new Intl.DateTimeFormat("it-IT", { hour: "2-digit", minute: "2-digit", timeZone: "Europe/Rome" }).format(new Date(iso));

export default function Tasks({ client, pipeline, meName, admin, onOpenLead }: { client: Client; pipeline: Pipeline | null; meName: string; admin: boolean; onOpenLead: (lead: Lead) => void }) {
  const [tasks, setTasks] = useState<SalesTask[]>([]); const [leads, setLeads] = useState<Lead[]>([]); const [stages, setStages] = useState<Stage[]>([]); const [view, setView] = useState<View>("today"); const [editing, setEditing] = useState<SalesTask | "new" | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const today = romeToday();
  const load = useCallback(async () => { const [a, b, c] = await Promise.all([supabase.from("sales_tasks").select("*").eq("client_id", client.id).order("due_at"), supabase.from("leads").select("*").eq("client_id", client.id), supabase.from("stages").select("*").eq("client_id", client.id).order("position")]); setError(a.error?.message ?? null); setTasks((a.data as SalesTask[]) ?? []); setLeads((b.data as Lead[]) ?? []); setStages((c.data as Stage[]) ?? []); }, [client.id]);
  useEffect(() => { void load(); }, [load]);
  const leadById = useMemo(() => new Map(leads.map((l) => [l.id, l])), [leads]); const stageById = useMemo(() => new Map(stages.map((s) => [s.id, s])), [stages]);
  const scoped = tasks.filter((t) => !pipeline || !t.lead_id || leadById.get(t.lead_id)?.pipeline_id === pipeline.id); const open = scoped.filter((t) => !t.completed_at); const late = open.filter((t) => dayOf(t.due_at) < today); const todayTasks = open.filter((t) => dayOf(t.due_at) === today); const future = open.filter((t) => dayOf(t.due_at) > today); const done = scoped.filter((t) => t.completed_at && dayOf(t.completed_at) === today);
  const activeLeads = leads.filter((l) => (!pipeline || l.pipeline_id === pipeline.id) && !["CLOSED", "LOST"].includes(stageById.get(l.stage_id)?.name ?? "")); const taskLeadIds = new Set(open.map((t) => t.lead_id).filter(Boolean)); const missing = activeLeads.filter((l) => !taskLeadIds.has(l.id)); const list = view === "today" ? [...late, ...todayTasks] : view === "future" ? future : view === "done" ? done : [];
  async function complete(task: SalesTask) { setBusy(true); const { error } = await supabase.from("sales_tasks").update({ completed_at: new Date().toISOString(), completed_by: meName }).eq("id", task.id); if (!error && task.lead_id) await supabase.from("lead_activities").insert({ lead_id: task.lead_id, client_id: client.id, activity_type: "follow_up", outcome: "Attività completata", note: task.title, created_by: meName }); setBusy(false); if (error) setError(error.message); else void load(); }
  return <div className="page tasks-page"><div className="tasks-intro"><div><h1>Agenda commerciale</h1><p>{admin ? "Preparazione della riunione mattutina: priorità personali e follow-up sui lead, con giorno e orario." : "La tua agenda operativa: task personali e follow-up dei tuoi lead."}</p></div><button className="btn primary" onClick={() => setEditing("new")}>+ Nuova attività</button></div><div className="task-kpis"><Kpi value={late.length} label="in ritardo" onClick={() => setView("today")} danger /><Kpi value={todayTasks.length} label="da fare oggi" onClick={() => setView("today")} /><Kpi value={future.length} label="in programma" onClick={() => setView("future")} /><Kpi value={missing.length} label="lead senza task" onClick={() => setView("missing")} warn /></div><div className="tasks-tabs"><button className={view === "today" ? "active" : ""} onClick={() => setView("today")}>Riunione mattutina</button><button className={view === "future" ? "active" : ""} onClick={() => setView("future")}>Agenda futura</button><button className={view === "missing" ? "active" : ""} onClick={() => setView("missing")}>Lead da pianificare</button><button className={view === "done" ? "active" : ""} onClick={() => setView("done")}>Completate oggi</button></div>{error && <div className="notice err">Agenda non ancora attiva: {error}</div>}{view === "missing" ? <Missing leads={missing} stages={stageById} onPlan={(lead) => setEditing({ id: "", client_id: client.id, lead_id: lead.id, title: `Follow-up — ${lead.name || "Lead senza nome"}`, description: null, due_at: new Date().toISOString(), assigned_to: lead.assigned_to || meName, created_by: meName, completed_at: null, completed_by: null, created_at: "", updated_at: "" })} /> : <TaskList list={list} leads={leadById} onEdit={setEditing} onOpen={onOpenLead} onComplete={(task) => void complete(task)} busy={busy} />}{editing && <TaskForm item={editing === "new" ? null : editing} leads={activeLeads} clientId={client.id} meName={meName} onClose={() => setEditing(null)} onSaved={() => { setEditing(null); void load(); }} />}</div>;
}

function Kpi({ value, label, onClick, danger, warn }: { value: number; label: string; onClick: () => void; danger?: boolean; warn?: boolean }) { return <button className={danger ? "danger" : warn ? "warn" : ""} onClick={onClick}><b>{value}</b><span>{label}</span></button>; }
function TaskList({ list, leads, onEdit, onOpen, onComplete, busy }: { list: SalesTask[]; leads: Map<string, Lead>; onEdit: (task: SalesTask) => void; onOpen: (lead: Lead) => void; onComplete: (task: SalesTask) => void; busy: boolean }) { if (!list.length) return <div className="tasks-empty"><b>Nessuna attività in questa vista.</b><span>Aggiungi una task personale o pianifica il prossimo passo di un lead.</span></div>; return <div className="task-list">{list.map((task) => { const lead = task.lead_id ? leads.get(task.lead_id) : null; return <article className={`task-card ${task.completed_at ? "completed" : dayOf(task.due_at) < romeToday() ? "overdue" : ""}`} key={task.id}><div className="task-date"><b>{timeOf(task.due_at)}</b><span>{new Date(task.due_at).toLocaleDateString("it-IT", { day: "2-digit", month: "short" })}</span></div><div className="task-lead"><b>{task.title}</b><span>{lead ? lead.name || "Lead senza nome" : "Task personale"} · {task.assigned_to}</span>{task.description && <small>{task.description}</small>}</div><div className="task-actions">{lead && <button className="btn small" onClick={() => onOpen(lead)}>Apri lead</button>}{!task.completed_at && <button className="btn small" onClick={() => onEdit(task)}>Modifica</button>}{!task.completed_at && <button className="btn small done" disabled={busy} onClick={() => onComplete(task)}>Fatto</button>}</div></article>; })}</div>; }
function Missing({ leads, stages, onPlan }: { leads: Lead[]; stages: Map<string, Stage>; onPlan: (lead: Lead) => void }) { if (!leads.length) return <div className="tasks-empty"><b>Tutti i lead attivi hanno almeno una prossima attività.</b><span>La pipeline è sotto controllo.</span></div>; return <div className="task-list">{leads.map((lead) => <article className="task-card overdue" key={lead.id}><div className="task-date"><b>—</b><span>Da fissare</span></div><div className="task-lead"><b>{lead.name || "Lead senza nome"}</b><span>{stages.get(lead.stage_id)?.name || "Fase non definita"}{lead.phone ? ` · ${lead.phone}` : ""}</span></div><div className="task-actions"><button className="btn small primary" onClick={() => onPlan(lead)}>Pianifica</button></div></article>)}</div>; }
function TaskForm({ item, leads, clientId, meName, onClose, onSaved }: { item: SalesTask | null; leads: Lead[]; clientId: string; meName: string; onClose: () => void; onSaved: () => void }) { const [title, setTitle] = useState(item?.title ?? ""); const [leadId, setLeadId] = useState(item?.lead_id ?? ""); const [due, setDue] = useState(localDateTime(item?.due_at ? new Date(item.due_at) : new Date())); const [description, setDescription] = useState(item?.description ?? ""); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); async function save() { if (!title.trim() || !due) return setError("Inserisci attività, data e ora."); setBusy(true); const data = { title: title.trim(), lead_id: leadId || null, due_at: new Date(due).toISOString(), description: description.trim() || null, assigned_to: item?.assigned_to || meName, created_by: item?.created_by || meName }; const res = item?.id ? await supabase.from("sales_tasks").update(data).eq("id", item.id) : await supabase.from("sales_tasks").insert({ ...data, client_id: clientId }); if (!res.error && leadId) await supabase.from("leads").update({ next_action_date: due.slice(0, 10) }).eq("id", leadId); setBusy(false); if (res.error) setError(res.error.message); else onSaved(); } return <div className="overlay" onClick={onClose}><div className="modal task-planner" onClick={(e) => e.stopPropagation()}><header><div><h3>{item?.id ? "Modifica attività" : "Nuova attività"}</h3><p>Usa una task personale oppure collegala a un lead.</p></div><button className="x" onClick={onClose}>×</button></header><div className="content">{error && <div className="notice err">{error}</div>}<div className="field"><label>Cosa deve essere fatto?</label><input autoFocus value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Es. Preparare scaletta call, richiamare Marta…" /></div><div className="field"><label>Collega a un lead <small>(facoltativo)</small></label><select value={leadId} onChange={(e) => { setLeadId(e.target.value); const lead = leads.find((x) => x.id === e.target.value); if (lead && !title) setTitle(`Follow-up — ${lead.name || "Lead"}`); }}><option value="">Task personale</option>{leads.map((lead) => <option value={lead.id} key={lead.id}>{lead.name || "Lead senza nome"}</option>)}</select></div><div className="field"><label>Data e orario</label><input type="datetime-local" value={due} onChange={(e) => setDue(e.target.value)} /></div><div className="field"><label>Dettagli <small>(facoltativo)</small></label><textarea value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Cosa serve sapere prima di svolgerla?" /></div></div><footer><button className="btn" onClick={onClose}>Annulla</button><button className="btn primary" disabled={busy} onClick={() => void save()}>{busy ? "Salvataggio…" : "Salva attività"}</button></footer></div></div>; }
